const FORMAT_DATE_NORMAL = 'DD/MM/YYYY';

const FORMAT_DATETIME = 'DD/MM/YYYY HH:mm:ss';

const FORMAT_TIME_SHORT = 'HH:mm';

const FORMAT_DATE_MONTH = 'DD/MM';

const FORMAT_MONTH_NORMAL = 'MM/YYYY';

const MINIMUM_YEAR = 18;

export {
  FORMAT_DATE_MONTH,
  FORMAT_DATE_NORMAL,
  FORMAT_MONTH_NORMAL,
  FORMAT_DATETIME,
  FORMAT_TIME_SHORT,
  MINIMUM_YEAR,
};
